import React from "react";
import Coresub from "./Coresub";

export default function CS208() {
  const elejune23 = {
    date: " 11 jun 2023",
    firsttitle: "finite automata",
    firstbody: [
      <>
        <h3>
          two types of finite Automate
        </h3>
        <ul>
          <li>deterministic automata</li>
          <li>non-deterministic automata</li>
        </ul>
       
        <p><b>you see i dont want to type anymore its not the optimal way therefore ill just provide the link of this topic (good one)</b></p>
        <h4> <a href="https://www.geeksforgeeks.org/introduction-of-finite-automata/" rel="noreferrer" target="_blank"> click </a> to learn about finite automata</h4>
        <h3>learn how to convert non-deterministic finite automata to deterministic finite automata</h3>
        <a href=""> click to learn</a>
      </>,
    ],
  };
  const _16jun23 ={
    date: "16 jan 2023",
    firstbody: [
      <>
      <h3></h3>
      <h3>sir gave some questions on this date the are given</h3>
      <ol>
        <li>design a fininte automata where each string generated by the language will end with 0 1</li>
        <li>design and automata where it will end in either 00 or 11</li>

        <li>design a finite automata which have exactly 4 1 in every string</li>
        <li>design a finite automata which accepts string containing exactly one 1 in the final string</li>
        
      </ol>
      <p>sir also thold us to learn about regular set <a href="">click</a></p>
      </>
    ]
  }
  return (
    <div  className="d-flex flex-column">
      <Coresub date={elejune23.date} firsttitle={elejune23.firsttitle} firstbody={elejune23.firstbody}/>
      <Coresub date= "12 june 2023" firsttitle="mass bunk was conducted due to scarcity of water"/>
      <Coresub date= "13 june 2023" firsttitle="mass bunk was conducted due to scarcity of water"/>
      <Coresub date= {_16jun23.date} firsttitle={_16jun23.firstbody}/>
    </div>

  );
}
